runtime: php
env: flex

runtime_config: document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:U4TkTwnTzgCW6X7uQa2eN5/dnRq2ZyC7DT5IJLF40S8=
    APP_NAME: "GCP App - CODE"

    LOG_LEVEL: debug
